version: '3.8'
services:
  app:
    build: .
    container_name: taskmanagers
    volumes:
      - db-data:/app/Data
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  db-data:
    name: taskmanagers_data